name: Aptos binary builder
run-name: Aptos binary builder
on: [push]
permissions:
  contents: write

env:
  APTOS_VERSION: v1.23.2-rc

jobs:
  build-aptos-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "aptos-labs/aptos-core"
          ref: "aptos-node-${{ env.APTOS_VERSION }}"
      - run: "./scripts/dev_setup.sh -b"
      - run: cargo build --package aptos-node --profile release
      - run: tar -czvf aptos-node-${{ env.APTOS_VERSION }}.tgz -C target/release/ aptos-node
      - uses: actions/upload-artifact@v3
        with:
          name: "aptos-node-${{ env.APTOS_VERSION }}.tgz"
          path: "aptos-node-${{ env.APTOS_VERSION }}.tgz"
  build-aptos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "aptos-labs/aptos-core"
          ref: "aptos-node-${{ env.APTOS_VERSION }}"
      - run: "./scripts/dev_setup.sh -b"
      - run: cargo build --package aptos --profile release
      - run: tar -czvf aptos-${{ env.APTOS_VERSION }}.tgz -C target/release/ aptos
      - uses: actions/upload-artifact@v3
        with:
          name: "aptos-${{ env.APTOS_VERSION }}.tgz"
          path: "aptos-${{ env.APTOS_VERSION }}.tgz"
  release:
    runs-on: ubuntu-latest
    needs: [build-aptos-node,build-aptos]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "aptos-node-${{ env.APTOS_VERSION }}.tgz"
      - uses: actions/download-artifact@v3
        with:
          name: "aptos-${{ env.APTOS_VERSION }}.tgz"
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            aptos-node-${{ env.APTOS_VERSION }}.tgz
            aptos-${{ env.APTOS_VERSION }}.tgz
          tag_name: "aptos-binary-${{ env.APTOS_VERSION }}"